# Generated by Django 6.1.1 on 2026-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
